### Using polars instead of pandas

In [1]:
!pip install polars

Requirement already satisfied: polars in /home/kid/miniconda3/lib/python3.13/site-packages (1.39.3)
Requirement already satisfied: polars-runtime-32==1.39.3 in /home/kid/miniconda3/lib/python3.13/site-packages (from polars) (1.39.3)

In [2]:
import polars as pl

In [3]:
df = pl.read_csv('StudentPerformanceFactors.csv')
df.head()

shape: (5, 20)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬────────┬───────────┐
│ Hours_Stud ┆ Attendance ┆ Parental_ ┆ Access_to ┆ … ┆ Parental_ ┆ Distance_ ┆ Gender ┆ Exam_Scor │
│ ied        ┆ ---        ┆ Involveme ┆ _Resource ┆   ┆ Education ┆ from_Home ┆ ---    ┆ e         │
│ ---        ┆ i64        ┆ nt        ┆ s         ┆   ┆ _Level    ┆ ---       ┆ str    ┆ ---       │
│ i64        ┆            ┆ ---       ┆ ---       ┆   ┆ ---       ┆ str       ┆        ┆ i64       │
│            ┆            ┆ str       ┆ str       ┆   ┆ str       ┆           ┆        ┆           │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪════════╪═══════════╡
│ 23         ┆ 84         ┆ Low       ┆ High      ┆ … ┆ High      ┆ Near      ┆ Male   ┆ 67        │
│            ┆            ┆           ┆           ┆   ┆ School    ┆           ┆        ┆           │
│ 19         ┆ 64         ┆ Low       ┆ Medium    ┆ … ┆ College   ┆ Moderate  ┆ Female ┆ 61        │
│ 24         ┆ 98         ┆ Medium    ┆ Medium    ┆ … ┆ Postgradu ┆ Near      ┆ Male   ┆ 74        │
│            ┆            ┆           ┆           ┆   ┆ ate       ┆           ┆        ┆           │
│ 29         ┆ 89         ┆ Low       ┆ Medium    ┆ … ┆ High      ┆ Moderate  ┆ Male   ┆ 71        │
│            ┆            ┆           ┆           ┆   ┆ School    ┆           ┆        ┆           │
│ 19         ┆ 92         ┆ Medium    ┆ Medium    ┆ … ┆ College   ┆ Near      ┆ Female ┆ 70        │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴────────┴───────────┘

In [4]:
df.describe()

shape: (9, 21)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬────────┬───────────┐
│ statistic  ┆ Hours_Stud ┆ Attendanc ┆ Parental_ ┆ … ┆ Parental_ ┆ Distance_ ┆ Gender ┆ Exam_Scor │
│ ---        ┆ ied        ┆ e         ┆ Involveme ┆   ┆ Education ┆ from_Home ┆ ---    ┆ e         │
│ str        ┆ ---        ┆ ---       ┆ nt        ┆   ┆ _Level    ┆ ---       ┆ str    ┆ ---       │
│            ┆ f64        ┆ f64       ┆ ---       ┆   ┆ ---       ┆ str       ┆        ┆ f64       │
│            ┆            ┆           ┆ str       ┆   ┆ str       ┆           ┆        ┆           │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪════════╪═══════════╡
│ count      ┆ 6607.0     ┆ 6607.0    ┆ 6607      ┆ … ┆ 6517      ┆ 6540      ┆ 6607   ┆ 6607.0    │
│ null_count ┆ 0.0        ┆ 0.0       ┆ 0         ┆ … ┆ 90        ┆ 67        ┆ 0      ┆ 0.0       │
│ mean       ┆ 19.975329  ┆ 79.977448 ┆ null      ┆ … ┆ null      ┆ null      ┆ null   ┆ 67.235659 │
│ std        ┆ 5.990594   ┆ 11.547475 ┆ null      ┆ … ┆ null      ┆ null      ┆ null   ┆ 3.890456  │
│ min        ┆ 1.0        ┆ 60.0      ┆ High      ┆ … ┆ College   ┆ Far       ┆ Female ┆ 55.0      │
│ 25%        ┆ 16.0       ┆ 70.0      ┆ null      ┆ … ┆ null      ┆ null      ┆ null   ┆ 65.0      │
│ 50%        ┆ 20.0       ┆ 80.0      ┆ null      ┆ … ┆ null      ┆ null      ┆ null   ┆ 67.0      │
│ 75%        ┆ 24.0       ┆ 90.0      ┆ null      ┆ … ┆ null      ┆ null      ┆ null   ┆ 69.0      │
│ max        ┆ 44.0       ┆ 100.0     ┆ Medium    ┆ … ┆ Postgradu ┆ Near      ┆ Male   ┆ 101.0     │
│            ┆            ┆           ┆           ┆   ┆ ate       ┆           ┆        ┆           │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴────────┴───────────┘

In [5]:
df = df.with_columns(
    (pl.col("Exam_Score") > 70).cast(pl.Int8).alias("result")
)

In [6]:
df.head()

shape: (5, 21)
┌────────────┬────────────┬────────────┬────────────┬───┬────────────┬────────┬───────────┬────────┐
│ Hours_Stud ┆ Attendance ┆ Parental_I ┆ Access_to_ ┆ … ┆ Distance_f ┆ Gender ┆ Exam_Scor ┆ result │
│ ied        ┆ ---        ┆ nvolvement ┆ Resources  ┆   ┆ rom_Home   ┆ ---    ┆ e         ┆ ---    │
│ ---        ┆ i64        ┆ ---        ┆ ---        ┆   ┆ ---        ┆ str    ┆ ---       ┆ i8     │
│ i64        ┆            ┆ str        ┆ str        ┆   ┆ str        ┆        ┆ i64       ┆        │
╞════════════╪════════════╪════════════╪════════════╪═══╪════════════╪════════╪═══════════╪════════╡
│ 23         ┆ 84         ┆ Low        ┆ High       ┆ … ┆ Near       ┆ Male   ┆ 67        ┆ 0      │
│ 19         ┆ 64         ┆ Low        ┆ Medium     ┆ … ┆ Moderate   ┆ Female ┆ 61        ┆ 0      │
│ 24         ┆ 98         ┆ Medium     ┆ Medium     ┆ … ┆ Near       ┆ Male   ┆ 74        ┆ 1      │
│ 29         ┆ 89         ┆ Low        ┆ Medium     ┆ … ┆ Moderate   ┆ Male   ┆ 71        ┆ 1      │
│ 19         ┆ 92         ┆ Medium     ┆ Medium     ┆ … ┆ Near       ┆ Female ┆ 70        ┆ 0      │
└────────────┴────────────┴────────────┴────────────┴───┴────────────┴────────┴───────────┴────────┘

In [7]:
df.columns

['Hours_Studied',
 'Attendance',
 'Parental_Involvement',
 'Access_to_Resources',
 'Extracurricular_Activities',
 'Sleep_Hours',
 'Previous_Scores',
 'Motivation_Level',
 'Internet_Access',
 'Tutoring_Sessions',
 'Family_Income',
 'Teacher_Quality',
 'School_Type',
 'Peer_Influence',
 'Physical_Activity',
 'Learning_Disabilities',
 'Parental_Education_Level',
 'Distance_from_Home',
 'Gender',
 'Exam_Score',
 'result']

In [8]:
df = df.drop([
 'Parental_Involvement',
 'Access_to_Resources',
 'Motivation_Level',
 'Internet_Access',
 'Tutoring_Sessions',
 'Family_Income',
 'Teacher_Quality',
 'School_Type',
 'Peer_Influence',
 'Learning_Disabilities',
 'Parental_Education_Level',
 'Distance_from_Home',
 'Gender',
 'Exam_Score'])

In [9]:
df.head()

shape: (5, 7)
┌───────────────┬────────────┬───────────────┬─────────────┬───────────────┬──────────────┬────────┐
│ Hours_Studied ┆ Attendance ┆ Extracurricul ┆ Sleep_Hours ┆ Previous_Scor ┆ Physical_Act ┆ result │
│ ---           ┆ ---        ┆ ar_Activities ┆ ---         ┆ es            ┆ ivity        ┆ ---    │
│ i64           ┆ i64        ┆ ---           ┆ i64         ┆ ---           ┆ ---          ┆ i8     │
│               ┆            ┆ str           ┆             ┆ i64           ┆ i64          ┆        │
╞═══════════════╪════════════╪═══════════════╪═════════════╪═══════════════╪══════════════╪════════╡
│ 23            ┆ 84         ┆ No            ┆ 7           ┆ 73            ┆ 3            ┆ 0      │
│ 19            ┆ 64         ┆ No            ┆ 8           ┆ 59            ┆ 4            ┆ 0      │
│ 24            ┆ 98         ┆ Yes           ┆ 7           ┆ 91            ┆ 4            ┆ 1      │
│ 29            ┆ 89         ┆ Yes           ┆ 8           ┆ 98            ┆ 4            ┆ 1      │
│ 19            ┆ 92         ┆ Yes           ┆ 6           ┆ 65            ┆ 4            ┆ 0      │
└───────────────┴────────────┴───────────────┴─────────────┴───────────────┴──────────────┴────────┘

In [10]:
df = df.with_columns(
    pl.col("Extracurricular_Activities").cast(pl.Categorical).to_physical()
)

In [11]:
df.head()

shape: (5, 7)
┌───────────────┬────────────┬───────────────┬─────────────┬───────────────┬──────────────┬────────┐
│ Hours_Studied ┆ Attendance ┆ Extracurricul ┆ Sleep_Hours ┆ Previous_Scor ┆ Physical_Act ┆ result │
│ ---           ┆ ---        ┆ ar_Activities ┆ ---         ┆ es            ┆ ivity        ┆ ---    │
│ i64           ┆ i64        ┆ ---           ┆ i64         ┆ ---           ┆ ---          ┆ i8     │
│               ┆            ┆ u32           ┆             ┆ i64           ┆ i64          ┆        │
╞═══════════════╪════════════╪═══════════════╪═════════════╪═══════════════╪══════════════╪════════╡
│ 23            ┆ 84         ┆ 0             ┆ 7           ┆ 73            ┆ 3            ┆ 0      │
│ 19            ┆ 64         ┆ 0             ┆ 8           ┆ 59            ┆ 4            ┆ 0      │
│ 24            ┆ 98         ┆ 1             ┆ 7           ┆ 91            ┆ 4            ┆ 1      │
│ 29            ┆ 89         ┆ 1             ┆ 8           ┆ 98            ┆ 4            ┆ 1      │
│ 19            ┆ 92         ┆ 1             ┆ 6           ┆ 65            ┆ 4            ┆ 0      │
└───────────────┴────────────┴───────────────┴─────────────┴───────────────┴──────────────┴────────┘

In [13]:
df.describe()

shape: (9, 8)
┌────────────┬────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬──────────┐
│ statistic  ┆ Hours_Stud ┆ Attendance ┆ Extracurri ┆ Sleep_Hou ┆ Previous_ ┆ Physical_ ┆ result   │
│ ---        ┆ ied        ┆ ---        ┆ cular_Acti ┆ rs        ┆ Scores    ┆ Activity  ┆ ---      │
│ str        ┆ ---        ┆ f64        ┆ vities     ┆ ---       ┆ ---       ┆ ---       ┆ f64      │
│            ┆ f64        ┆            ┆ ---        ┆ f64       ┆ f64       ┆ f64       ┆          │
│            ┆            ┆            ┆ f64        ┆           ┆           ┆           ┆          │
╞════════════╪════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪══════════╡
│ count      ┆ 6607.0     ┆ 6607.0     ┆ 6607.0     ┆ 6607.0    ┆ 6607.0    ┆ 6607.0    ┆ 6607.0   │
│ null_count ┆ 0.0        ┆ 0.0        ┆ 0.0        ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ mean       ┆ 19.975329  ┆ 79.977448  ┆ 0.596035   ┆ 7.02906   ┆ 75.070531 ┆ 2.96761   ┆ 0.163917 │
│ std        ┆ 5.990594   ┆ 11.547475  ┆ 0.490728   ┆ 1.46812   ┆ 14.399784 ┆ 1.031231  ┆ 0.370228 │
│ min        ┆ 1.0        ┆ 60.0       ┆ 0.0        ┆ 4.0       ┆ 50.0      ┆ 0.0       ┆ 0.0      │
│ 25%        ┆ 16.0       ┆ 70.0       ┆ 0.0        ┆ 6.0       ┆ 63.0      ┆ 2.0       ┆ 0.0      │
│ 50%        ┆ 20.0       ┆ 80.0       ┆ 1.0        ┆ 7.0       ┆ 75.0      ┆ 3.0       ┆ 0.0      │
│ 75%        ┆ 24.0       ┆ 90.0       ┆ 1.0        ┆ 8.0       ┆ 88.0      ┆ 4.0       ┆ 0.0      │
│ max        ┆ 44.0       ┆ 100.0      ┆ 1.0        ┆ 10.0      ┆ 100.0     ┆ 6.0       ┆ 1.0      │
└────────────┴────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴──────────┘

In [14]:
df.head()

shape: (5, 7)
┌───────────────┬────────────┬───────────────┬─────────────┬───────────────┬──────────────┬────────┐
│ Hours_Studied ┆ Attendance ┆ Extracurricul ┆ Sleep_Hours ┆ Previous_Scor ┆ Physical_Act ┆ result │
│ ---           ┆ ---        ┆ ar_Activities ┆ ---         ┆ es            ┆ ivity        ┆ ---    │
│ i64           ┆ i64        ┆ ---           ┆ i64         ┆ ---           ┆ ---          ┆ i8     │
│               ┆            ┆ u32           ┆             ┆ i64           ┆ i64          ┆        │
╞═══════════════╪════════════╪═══════════════╪═════════════╪═══════════════╪══════════════╪════════╡
│ 23            ┆ 84         ┆ 0             ┆ 7           ┆ 73            ┆ 3            ┆ 0      │
│ 19            ┆ 64         ┆ 0             ┆ 8           ┆ 59            ┆ 4            ┆ 0      │
│ 24            ┆ 98         ┆ 1             ┆ 7           ┆ 91            ┆ 4            ┆ 1      │
│ 29            ┆ 89         ┆ 1             ┆ 8           ┆ 98            ┆ 4            ┆ 1      │
│ 19            ┆ 92         ┆ 1             ┆ 6           ┆ 65            ┆ 4            ┆ 0      │
└───────────────┴────────────┴───────────────┴─────────────┴───────────────┴──────────────┴────────┘

In [15]:
df_analysis = df.to_pandas()

### Automated EDA

In [16]:
from ydata_profiling import ProfileReport

profile = ProfileReport(df_analysis, title="Student Analysis Report")
profile.to_file("analysis_report.html")

100%|██████████| 7/7 [00:00<00:00, 1812.35it/s]<00:00, 20.94it/s, Describe variable: Physical_Activity]
Summarize dataset:  64%|██████▍   | 9/14 [00:00<00:00, 99.07it/s, Calculate auto correlation]          /home/kid/miniconda3/lib/python3.13/site-packages/ydata_profiling/model/pandas/discretize_pandas.py:52: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0 0 9 ... 0 0 0]' has dtype incompatible with int8, please explicitly cast to a compatible dtype first.
  discretized_df.loc[:, column] = self._discretize_column(
Summarize dataset: 100%|██████████| 41/41 [00:01<00:00, 25.22it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:00<00:00,  1.42it/s]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  7.32it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 320.25it/s]

In [17]:
df = df.unique()

In [18]:
df_analysis = df.to_pandas()

profile = ProfileReport(df_analysis, title="Student Analysis Report")
profile.to_file("analysis_report.html")

100%|██████████| 7/7 [00:00<00:00, 2921.99it/s]<?, ?it/s, Describe variable: result]
Summarize dataset:  64%|██████▍   | 9/14 [00:00<00:00, 113.02it/s, Calculate auto correlation]/home/kid/miniconda3/lib/python3.13/site-packages/ydata_profiling/model/pandas/discretize_pandas.py:52: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[9 9 9 ... 0 0 0]' has dtype incompatible with int8, please explicitly cast to a compatible dtype first.
  discretized_df.loc[:, column] = self._discretize_column(
Summarize dataset: 100%|██████████| 41/41 [00:01<00:00, 26.32it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:00<00:00,  1.40it/s]
Render HTML: 100%|██████████| 1/1 [00:00<00:00, 17.18it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 463.41it/s]

In [19]:
df.head()

shape: (5, 7)
┌───────────────┬────────────┬───────────────┬─────────────┬───────────────┬──────────────┬────────┐
│ Hours_Studied ┆ Attendance ┆ Extracurricul ┆ Sleep_Hours ┆ Previous_Scor ┆ Physical_Act ┆ result │
│ ---           ┆ ---        ┆ ar_Activities ┆ ---         ┆ es            ┆ ivity        ┆ ---    │
│ i64           ┆ i64        ┆ ---           ┆ i64         ┆ ---           ┆ ---          ┆ i8     │
│               ┆            ┆ u32           ┆             ┆ i64           ┆ i64          ┆        │
╞═══════════════╪════════════╪═══════════════╪═════════════╪═══════════════╪══════════════╪════════╡
│ 28            ┆ 91         ┆ 0             ┆ 7           ┆ 90            ┆ 3            ┆ 1      │
│ 34            ┆ 93         ┆ 1             ┆ 6           ┆ 93            ┆ 4            ┆ 1      │
│ 18            ┆ 90         ┆ 1             ┆ 6           ┆ 54            ┆ 3            ┆ 1      │
│ 31            ┆ 65         ┆ 1             ┆ 7           ┆ 71            ┆ 4            ┆ 0      │
│ 18            ┆ 90         ┆ 0             ┆ 6           ┆ 88            ┆ 1            ┆ 0      │
└───────────────┴────────────┴───────────────┴─────────────┴───────────────┴──────────────┴────────┘

### Making data ready for model

In [20]:
X = df.drop("result").to_pandas()
y = df["result"].to_pandas()

In [21]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=20)

### Pipeline

In [22]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

In [30]:
pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('model', LogisticRegression(solver='liblinear'))
])

In [31]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('model', LogisticRegression(solver='liblinear'))])

In [32]:
from sklearn.model_selection import cross_val_score

cross_val_score(pipeline, X, y, cv=5)

array([0.91212121, 0.9       , 0.90757576, 0.89469697, 0.90144049])

In [33]:
from sklearn.model_selection import GridSearchCV

params = {
    'model__penalty': ['l1', 'l2'],
    'model__C': [1, 2, 3, 4, 5, 10, 20]
}

grid = GridSearchCV(pipeline, param_grid=params, cv=5)
grid.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('model',
                                        LogisticRegression(solver='liblinear'))]),
             param_grid={'model__C': [1, 2, 3, 4, 5, 10, 20],
                         'model__penalty': ['l1', 'l2']})

In [34]:
grid.best_params_

{'model__C': 3, 'model__penalty': 'l1'}

### Final Pipeline with best parameters

In [35]:
pipeline_main = Pipeline([
    ('scaler', StandardScaler()),
    ('model', LogisticRegression(penalty='l1', C=3, solver='liblinear'))
])

In [36]:
pipeline_main.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('model',
                 LogisticRegression(C=3, penalty='l1', solver='liblinear'))])

### Evaluation with accuracy score

In [37]:
from sklearn.metrics import accuracy_score

y_pred = pipeline_main.predict(X_test)
accuracy_score(y_test, y_pred)

0.907070707070707

90.7% accuracy