In [6]:
import pandas as pd

In [7]:
df = pd.read_csv("StudentPerformanceFactors.csv")
df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70

In [8]:
df.columns

Index(['Hours_Studied', 'Attendance', 'Parental_Involvement',
       'Access_to_Resources', 'Extracurricular_Activities', 'Sleep_Hours',
       'Previous_Scores', 'Motivation_Level', 'Internet_Access',
       'Tutoring_Sessions', 'Family_Income', 'Teacher_Quality', 'School_Type',
       'Peer_Influence', 'Physical_Activity', 'Learning_Disabilities',
       'Parental_Education_Level', 'Distance_from_Home', 'Gender',
       'Exam_Score'],
      dtype='object')

In [9]:
df = df.drop(columns=['Parental_Involvement', 'Access_to_Resources','Internet_Access',
       'Tutoring_Sessions', 'Family_Income', 'Teacher_Quality', 'School_Type',
       'Peer_Influence', 'Physical_Activity', 'Learning_Disabilities',
       'Parental_Education_Level', 'Distance_from_Home'], axis=1)

In [10]:
df.head()

,Hours_Studied,Attendance,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Gender,Exam_Score
0,23,84,No,7,73,Low,Male,67
1,19,64,No,8,59,Low,Female,61
2,24,98,Yes,7,91,Medium,Male,74
3,29,89,Yes,8,98,Medium,Male,71
4,19,92,Yes,6,65,Medium,Female,70

In [14]:
from sklearn.preprocessing import LabelEncoder

In [15]:
le = LabelEncoder()

In [16]:
df["Extracurricular_Activities"] = le.fit_transform(df["Extracurricular_Activities"])
df.head()

,Hours_Studied,Attendance,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Gender,Exam_Score
0,23,84,0,7,73,Low,Male,67
1,19,64,0,8,59,Low,Female,61
2,24,98,1,7,91,Medium,Male,74
3,29,89,1,8,98,Medium,Male,71
4,19,92,1,6,65,Medium,Female,70

In [17]:
df["Motivation_Level"] = le.fit_transform(df["Motivation_Level"])
df.head()

,Hours_Studied,Attendance,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Gender,Exam_Score
0,23,84,0,7,73,1,Male,67
1,19,64,0,8,59,1,Female,61
2,24,98,1,7,91,2,Male,74
3,29,89,1,8,98,2,Male,71
4,19,92,1,6,65,2,Female,70

In [18]:
df["Gender"] = le.fit_transform(df["Gender"])
df.head()

,Hours_Studied,Attendance,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Gender,Exam_Score
0,23,84,0,7,73,1,1,67
1,19,64,0,8,59,1,0,61
2,24,98,1,7,91,2,1,74
3,29,89,1,8,98,2,1,71
4,19,92,1,6,65,2,0,70

In [19]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=["Exam_Score"], axis=1), df["Exam_Score"], test_size=0.3)

In [20]:
from sklearn.tree import DecisionTreeRegressor

In [24]:
tree2 = DecisionTreeRegressor(max_depth=2)

tree2.fit(X_train, y_train)

y_pred2_train = tree2.predict(X_train)
y_pred2_test = tree2.predict(X_test)

In [25]:
tree20 = DecisionTreeRegressor(max_depth=20)

tree20.fit(X_train, y_train)

y_pred20_train = tree20.predict(X_train)
y_pred20_test = tree20.predict(X_test)

In [26]:
from sklearn.metrics import mean_squared_error, r2_score

In [27]:
mse2_train = mean_squared_error(y_train, y_pred2_train)
mse2_test = mean_squared_error(y_test, y_pred2_test)

r2_train = r2_score(y_train, y_pred2_train)
r2_test = r2_score(y_test, y_pred2_test)

In [28]:
mse20_train = mean_squared_error(y_train, y_pred20_train)
mse20_test = mean_squared_error(y_test, y_pred20_test)

r20_train = r2_score(y_train, y_pred20_train)
r20_test = r2_score(y_test, y_pred20_test)

In [31]:
print(f"""
      max_depth = 2
Training: 
    MSE -> {mse2_train}
    r2  -> {r2_train*100}
Testing:
    MSE -> {mse2_test}
    r2  -> {r2_test*100}

    
      max_depth = 20
Training: 
    MSE -> {mse20_train}
    r2  -> {r20_train*100}
Testing:
    MSE -> {mse20_test}
    r2  -> {r20_test*100}
""")

      max_depth = 2
Training:
    MSE -> 9.787935778139682
    r2  -> 36.5863370904738
Testing:
    MSE -> 8.708790061955597
    r2  -> 39.646422402198944


      max_depth = 20
Training:
    MSE -> 0.008400786785302356
    r2  -> 99.94557333911325
Testing:
    MSE -> 16.328975000657515
    r2  -> -13.162913881682869

### max_depth = 2 -> little bit underfitting
### max_depth = 20 -> overfitting